### ISSUE TITLE
The model test-suite imports ColouredPetriNets.

### ISSUE THREAD

**Issue by philderbeast** [azardilis/Chromar#21]
The model test-suite imports ColouredPetriNets. Is this right?

https://github.com/azardilis/Chromar/blob/523a033a1c773c54df197419686e3d1cd333b01b/models/model.hs#L1

**Comment by azardilis** [comment]
It's definitely not right. In fact, the whole file was a precursor the work on Chromar and does not even use the quasiquoter. We could either move the rules to the quasiquoter or remove this file.

**Comment by azardilis** [comment]
I think I will try to migrate since it's a nice example of a simple whole-plant model.

**Comment by azardilis** [comment]
Removed this as it was just an exploration before any implementation of Chromar so it's not worth keeping around: d291f27a2d7ccb6d0fd626c01038149a2c73f380
